### ISSUE TITLE
Adult Gallimimus doesn't leave footsteps when sprinting and turning.

### ISSUE THREAD

**Issue by ExtraNick** [TheIsleGame/bugs#102]
## Expected Behavior

Expected Adult Gallimimus to leave footsteps when sprinting and turning (Both actions at the same time).

## Current Behavior

Adult Gallimimus leaves no footsteps when sprinting and turning, consequently, making no sound either.

Video evidence:
https://youtu.be/zdom5LySafw

## Steps to reproduce

-Spawn as Gallimimus Adult
-Turn around with A or D while sprinting, making circles.
-Notice that no sound will be made and no footsteps will be left.

## Build Information
[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1925837/TheIsle.log)

> **Game Version:** 0.1.36.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ExtraHu3** [comment]
Fixed in 0.1.38.0 ( development )

However the same issue is now present on crouching. Also happens to juvenile and Hatchling stage now.
Video Evidence: https://www.youtube.com/watch?v=DU-b5JHGllY&feature=youtu.be

Can be reproduced this way:
-Spawn as Gallimimus (any stage)
-Turn around with A or D while crouching, making circles.
-Notice that no sound will be made and no footsteps will be left.
