### ISSUE TITLE
Footprint issues for multiple species

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#112]
## Expected Behavior

Footprints should line up with the contact area between the foot and the ground.

## Current Behavior

Footprints appear behind the foot. (All life stages.)

![image](https://user-images.githubusercontent.com/38515115/39012255-f1830986-43e1-11e8-82db-3f7e3c1c5b31.png)

## Steps to reproduce

Log in as carno and move forward.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1929408/TheIsle.log)

> **Game Version:** 0.1.36.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
This is likely to be an issue for more than the Carno. Have you checked the other species? If not then we can do that later.

**Comment by MortenSilver** [comment]
Not yet, but its on the to-do list.

**Comment by MortenSilver** [comment]
Additionally, carno slides forward when moving forward with every gait in all life stages.

**Comment by dinosauriac** [comment]
I get the feeling this is to do with growth, could be that the prints aren't being scaled properly by the dino's age.

**Comment by Souretsu** [comment]
Was actually testing this with Morten and recorded it, if it's of any assistance.  Was done as a 1.0 size Subadult Carno.

Link: https://youtu.be/kpyl1bJpXXU

**Comment by MortenSilver** [comment]
Here are some findings after a second look at carnivores:

Utah (Adult)
- does not make step noise or leave footprints when walking
- footprints are offset when trotting and sprinting
- slides forward when moving
- feet return to the old/T-pose for all roar animations except broadcast

Utah (Juvenile)
- does not make step noise or leave footprints when walking
- footprints are offset when trotting and sprinting
- slides forward when moving
- feet return to the old/T-pose for all roar animations

Utah (Hatchling)
- does not make step noise or leave footprints when walking and trotting
- footprints are offset when sprinting
- slides forward when moving
- feet return to the old/T-pose for all roar animations

T-rex (Adult and Sub)
- footprints are offset when moving
- some sliding when moving

T-rex (Juvenile)
- footprints are too small

T-rex (Hatchling)
- does not make step noise or leave footprints when walking
- footprints are too small
- footprints are offset when trotting and sprinting

Carno (Adult, Sub, Juvenile)
- footprints are offset when moving
- slides forward when moving

Carno (Hatchling)
- does not make step noise or leave footprints when walking
- footprints are offset when moving
- slides forward when moving

Giga (Adult, Sub)
- footprints are offset when moving
- no sliding but they do some funky foot pumps with every step

Giga (Juvenile, Hatchling)
- does not make step noise or leave footprints when walking
- footprints are offset when moving

Also, when switching from sprinting to either trotting or walking it is possible to make the dinosaur skip a footprint. Possible to replicate with any dinosaur.

**Comment by dinosauriac** [comment]
I'm pretty certain hatchlings DO make footstep sounds, I remember setting them up. They're just really _really_ quiet and you need to be right up close to them to hear. I've been on the fence about whether it's worth keeping them, since such tiny defenseless creatures could maybe use the advantage of not making noise when they move, and the current sounds are basically only audible to the hatchling players themselves. 

The "skipping" thing is a little difficult to fix without making the dinosaurs completely herky-jerky in their motions (i.e. removing blend times). Sprint-to-stop animations are something that's on the to-do list though. When those get added it should help mitigate the problem when going between movement speeds.

**Comment by MortenSilver** [comment]
Could the hatchling steps only be made audible to the user, as to not break immersion? But still make them silent for everyone else to give babies a chance.

**Comment by dinosauriac** [comment]
If I set them to be UI sounds, yeah. Unsure if I can do that without them being effected by the UI sound slider though, it might be a little strange if the control that adjusts the volume of button presses also changed the volume of your footsteps.

**Comment by dinosauriac** [comment]
I've done another pass through this list fixing all of the items that are legitimate problems, several things above have already been fixed in the interim as well. Going to call this one fixed. 

With regards to footprints being "offset" though, unless they're seriously out of position it doesn't seem like much of an issue at all. Half the time they appear that way because your dinosaur reverts back to its neutral position after walking, so the step will appear slightly ahead of you. Since both the prints and step effects are intertwined in one trigger event I usually just place them where they feel correct as opposed to having them line up perfectly, which can mean the prints are slightly out of alignment so that the sounds don't become muddied sometimes.

**Comment by Hypno123** [comment]
Closing this with the reasoning above.
