### ISSUE TITLE
Bubbling sounds from geysers can be heard anywhere on the map

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#134]
## Expected Behavior

Bubbling sounds should not be heard until close to the geysers.

## Current Behavior

Bubbling sounds can be heard from anywhere on the map.

https://www.youtube.com/watch?v=s2Luros1H7Q

## Steps to reproduce

1. Spawn as anything.
2. Listen to the faint bubble sounds from anywhere until close to the geysers.

## Build Information

> **Game Version:** 0.1.37.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Ah, whoops. That was actually the result of a typo. Wasn't the geysers, but on the water volume below it. The distance scaling was set to 64 instead of 6.4.. fixed.

**Comment by Hypno123** [comment]
Still apparent in 0.1.37.9

**Comment by dinosauriac** [comment]
Could you post a video of this or something? It can't be the bubbles. I do hear corpse flies long distance, though.

**Comment by Hypno123** [comment]
Updated report with video.

**Comment by dinosauriac** [comment]
Okay, i think i've nipped this one in the bud. Volume scaling behaves fine, the issue is attenuation scaling by distance. I don't quite understand why, but minor adjustments like a 0.1 boost to distance attenuation feels like it scales up ten times that amount. Maybe the scale for that is inverted somehow, either way, I've made sure that the max distance scale never exceeds 1.0 on all attenuation types now, which should hopefully resolve the problem.

**Comment by Hypno123** [comment]
Will close when confirmed fixed.
