### ISSUE TITLE
Sounds become too quiet with 7.1 surround sound

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#140]
## Expected Behavior

Sounds should always remain the same volume regardless of the player's audio configuration.

## Current Behavior

When using 7.1 surround sound, the sounds made by other players will become much quieter more quickly than using stereo sound.

https://www.youtube.com/watch?v=Z0Lha9m6Bp8

This causes quiet footsteps to be near impossible to hear until their character is next to the player.

## Steps to reproduce

1. Have a 7.1 surround sound headset.
2. Listen to other player's sounds - they become very quiet over a small distance.
3. Change to stereo sound and they will be the correct volume.

## Build Information

> **Game Version:** 0.1.38.0 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
I believe the older unreal audio engine we use is actually limited to 5.1, so that could potentially cause some differences when listening with a 7.1 setup. So this might be improved if/when we switch to the newer unreal audio engine. That said, the vast majority of players will be using a 2-channel stereo output when playing the game, so that's what the sound has generally been designed around.
