### ISSUE TITLE
Utahraptor juvenile/hatchling stops idle animation briefly while roaring

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#169]
## Expected Behavior

Roaring should have no effect on the animation that is being played.

## Current Behavior

Roaring currently causes the idle animation to stop playing as Utah juvenile/hatchling.

## Steps to reproduce

1. Spawn as Utah juvie/hatchling.
2. Stand still.
3. Press any roar and watch idle animation stop playing briefly.

## Build Information

> **Game Version:** 0.1.38.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Souretsu** [comment]
Didn't see this was already reported, was about to make a new one for it, lol.  I did record a video of it if needed. https://youtu.be/23BFKpKvy3c

**Comment by dinosauriac** [comment]
I've fixed this, but as a result you'll see more sliding during full body animations since they're re-targeted from the adult's. It's a necessary compromise unless we shell out for a custom rig for each life cycle stage. Only other way to compensate for that would be a complete set of new animations for the juvenile and hatchling.
