### ISSUE TITLE
Moon/Sunlight visible through landscape

### ISSUE THREAD

**Issue by NightHaven15** [TheIsleGame/bugs#189]
## Expected Behavior

The moon/sun should not shine through landscape.

## Current Behavior

![image](https://user-images.githubusercontent.com/39176353/39901723-4a8caf98-5498-11e8-8087-6165715f5eba.png)
Moon/Sunlight is shining through the landscape. 

## Steps to reproduce

1. Spawn as any dino.
2. Wait for dawn/dusk or night.
3. Look towards moon/sun. When it is behind landscape.

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
This is caused by the ultra dynamic sky's _Sun Light Intensity_ and _Moonlight Intensity_ settings (annoyingly there are multiple options with very similar names to these in the blueprint). These two values are not actually being adjusted over the course of the day, and act as a constant multiplier of the "edge highlight" applied to objects when looking towards the active directional light. 

I think we need to add some sort of curve to control this on the sun & moon. Setting the value to zero disables shadows, but adjusting it to something close (e.g. 0.01) hides the highlight with the shadows intact. If we could interpolate from the default intensity value of 4.5 to that lower value during sunrise (~660) and sunset (~1720) that might fix the problem. 

A note about Moonlight Intensity:

This value is currently set really low on Thenyaw (don't know about V3) since the default makes for very unrealistic lighting, with bright purplish glows on everything in a very narrow shaft of light looking towards the moon. Might be worth just clamping this to a really low amount, especially since nights are supposed to be getting darker now.

**Comment by Hypno123** [comment]
Fixed.
