### ISSUE TITLE
No water sounds when walking in shallow water

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#203]
## Expected Behavior

The walking in water sounds should play when walking through water.

## Current Behavior

Walking in water that is deep enough to touch the surface but not shallow enough to cause water effects results in normal footprint sounds being made. There should be sounds for feet moving through the water.

https://www.youtube.com/watch?v=pOddxA0RzQg

## Steps to reproduce

1. Spawn as anything.
2. Find water that is deep enough to touch the surface without swimming.
3. Walk across the water surface and notice the water makes no sound.

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
This is intentional at the moment. There needs to be a buffer before water interaction starts, otherwise you'd be clipping into the volume and causing splashes when standing on the shore. That's one of the reasons why there aren't many shallow bodies of water, and why the swamp has started to be deepened recently. 

The only workaround for this would be to assign the water physical material to the mud layer, so that water steps play when you walk on that surface type, but it would require getting rid of all mud in the map except for where it's directly underneath water. Assigning a water phys mat to the meshes used in the water volumes could technically also get around this, but that's been disabled for the time being because it clashes with the effects generated by the volume itself, with the foot trace length causing walking sounds to be heard while swimming.
