### ISSUE TITLE
V3 Swamp Sound Effect Localization (co-op with MortenSilver)

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#332]
## Expected Behavior

You hear splash sound effects correctly according to the distance and direction of the animal you are listening to moving in the water.

## Current Behavior

In certain spots in the swamp, your animal's sound effects will go silent. There are certain spots in the swamp where if another player sits there and listens, when your dino's water sound effects go silent, the other player can hear them VERY clearly (as if you were right beside them), even if you are out of range.

https://clips.twitch.tv/AggressiveCovertStarlingBabyRage  (In this video, Morten was extremely far away from me, on the other side of the swamp, but it works for all sorts of ranges. Coords not available at this time, so I did a spectator zoom-out to try to help you identify the location. )

Morten's POV: https://youtu.be/kFeW9H0wdBA

## Steps to reproduce

Need at least two users. One person sits has to find a spot where they do not make water sound effects. the other person has to sit in a specific spot to hear them.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.1 (dev- Official test server)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by MortenSilver** [comment]
https://www.youtube.com/watch?v=kFeW9H0wdBA

This is a video from my point of view. When the splashing is not audible, it plays at one of the points. We're guessing there's more than one, due to an instance where neither of us could hear my splashing.

**Comment by dinosauriac** [comment]
This is most likely an issue with concurrency, it's probable the max splash sound limit was reached on one user's end but not on the other's. Concurrency is a real pain in the neck with UE4 in that it usually just stops generating the sound entirely once it hits the cap. It's supposed to be a performance saving measure but I've had to turn it off in various places because it just breaks things.

**Comment by dinosauriac** [comment]
Ok, i've been experiencing something that might be related to this issue in the test level now. It's not that the audio is failing to play, but it plays in the wrong place? If you're in deep water the sound positioning is fine, but walking through the shallows the splash sounds play at one of the corners of the water volume instead of at your feet. 

Could be something to do with the particle trigger being misaligned, though i wouldn't have thought there'd be any sounds at all if that were the case. Will require some investigation.

**Comment by Hypno123** [comment]
Closing in favour of a more up-to-date report. (#477)
