### ISSUE TITLE
Character sheets with duplicate juveniles

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#426]
## Expected Behavior

In any character sheet, all of the dinosaurs shown will correlate with the lifestage you are currently in.

## Current Behavior

For the Gallimimus Character sheet, there are two juvenile gallis shown instead of hatchling-juvi-sub-adult (Or hatchling-juvi-adult, depending on intended growth for galli). The second juvi galli (the one closest to the adult galli) never highlights throughout the growth cycles and appears to be put in by accident.
![image](https://user-images.githubusercontent.com/32625368/47590215-493a9100-d931-11e8-8432-0e7c4421e158.png)

## Steps to reproduce

Be a gallimimus. Look at character sheet.

## Build Information

> **Game Version:**  0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Dryosaurus

![image](https://user-images.githubusercontent.com/30550499/47590407-1493fd00-d964-11e8-8a27-35a4063c0406.png)

Maiasaura

![image](https://user-images.githubusercontent.com/30550499/47590426-25447300-d964-11e8-832c-10956183a64c.png)

Parasaurolophus

![image](https://user-images.githubusercontent.com/30550499/47590444-2fff0800-d964-11e8-8485-e62b2a244eff.png)

Allosaurus

![image](https://user-images.githubusercontent.com/30550499/47590487-4e650380-d964-11e8-9072-8fe5329f846e.png)

Carnotaurus

![image](https://user-images.githubusercontent.com/30550499/47590532-6c326880-d964-11e8-97c9-3ad4833cba18.png)

Dilophosaurus

![image](https://user-images.githubusercontent.com/30550499/47590559-7e140b80-d964-11e8-8214-041d7b12f382.png)

Utahraptor

![image](https://user-images.githubusercontent.com/30550499/47590588-9d129d80-d964-11e8-9710-4b2fbda0ba3b.png)

**Comment by dinosauriac** [comment]
There is no special case setup currently to handle when a class does not have a certain life stage, so there are duplicates until that gets added. In the case of Utahraptor there's technically no duplication going on, it has custom images for juvenile and subadult that illuminate correctly, but since there's no official subadult stage for it I guess it does belong in the same issues block.

**Comment by Hypno123** [comment]
Ah okay. In that case removing the subadult from Utahraptor and preventing the duplicates from appearing on species that do not have that phase seems like the best way forward. 

No point having them on that screen if they are never illuminated.

**Comment by dinosauriac** [comment]
The issue with double juvenile images appearing when there aren't four life stages specified has been fixed with 0.1.52.1.

With the Carno, Allo and Utah though-even if they don't technically have an extra growth stage defined, the image will highlight at the appropriate time based on their current growth percentage. It seems like a waste of art to not use them to me.
