### ISSUE TITLE
Utahraptor uses wrong water footstep sound

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#50]
## Expected Behavior

The Utahraptor should have small water footstep sounds.

## Current Behavior

The Utahraptor currently uses the large dinosaur water footstep sound.

## Steps to reproduce

1. Spawn as Utah.
2. Go to water.
3. Step in the water and listen to the footstep sounds - it is for larger dinosaurs.

## Build Information

> **Game Version:** 0.1.35.2 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Interaction FX are determined based on the weight of the animal currently. However, dinosaur weights are all over the place and make no sense, with several dinos of similar size usually having wildly varying stats. Wading sounds are also incomplete currently, still working through those, just haven't had much time to finish them the past week. 

I'm actually considering disabling water interaction sounds for now until the footstep system is reworked. The water volume should really be hooking into that, since having the audio be triggered by motion is less reliable and doesn't sync well with the dinosaur's movement. It's fine for spawning the particles, but the sounds not so much.

**Comment by Hypno123** [comment]
Fixed.
