### ISSUE TITLE
"Extras" section : Selection window to big

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#97]
## Expected Behavior

The selection window should end where the word ends

## Current Behavior

The selection window continues until the red bar (see screenshot)

![selection window](https://user-images.githubusercontent.com/35146192/38777663-e131e478-40ab-11e8-94df-553813813a36.PNG)

## Steps to reproduce

1) Go to the main menu
2) Select the "Extras" section
3) Use the mouse to see until where the selection window stops by using the sound effect of it.

## Build Information

> **Game Version:** 0.1.36.8

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
We don't know what words will ultimately be used there, and it's intentionally fuzzy on the standard menu list as well so that you don't need to be pixel precise or move your mouse all the way over to select an option. There's nothing else that's clickable in that area of the screen usually, and message boxes are ordered on top so that there isn't a conflict between the two, so I don't know if this is really a problem.
